### ISSUE TITLE
Organization for Issue Boards and agree on workflow

### ISSUE THREAD

**Issue by stv0g** [VILLASframework/documentation#1]
In GitLab by @ghost on Mar 13, 2017, 04:54

@stvogel @markatk @m-mirz 
     
What do you think of using Issue Boards for work org and as a workflow tool in future?    
If you agree, you can find below some of my notes.     

Unfortunately, as far as I know, there is no a single Issue Board across group of projects, so we'll use boards for each project. 
But maybe it is good to have different stages of issue board for different projects.  

We should do the following to get started with Issue Boards:    
1. [ ]  Define and agree on workflow stages (labels to be used by issue board).     
1. [ ]  Label existing issues
     1. [x] VILLASnode
     1. [x] VILLASweb
     1. [X] VILLASfpga
     1. [X] VILLAScontroller    
1. [ ] Create issues for all active and future features/tasks
     1. [x] @stvogel      
     1. [x] @m-mirz 
     1. [x] @markatk 
     1. [x] @mstevic 
1. [ ] Priorities some of other labels to have some kind of sorting of issues within a stage on Issue Board (e.g. issues related to milestones should have a label that refers to a milestone - *milestone-label*)      
1. [ ] Agree on workflow (e.g. whenever an issue is created, label it with a proper label if you want it to appear on issue board, label it with a *milestone-label* in order to prioritize it within one stage on issue board...)         

---

# Workflow Stages
I would propose the following: ~"stage:backlog"  -> ~"stage:development"  -> ~"stage:testing"  -> ~"stage:demo-integration"  -> ~"stage:doc-and-review"  -> *issue closed*
  
~"stage:demo-integration"  would refer to a stage while a feature/functionality/bug fix is being tested/included in a demo example.    
Not all issues have to through the complete cycle, although that is the idea... but for example, some documentation tasks can go directly to ~"stage:doc-and-review"  stage.        
Please see Issue Board in VILLASnode project as an example and feel free to suggest and comment.     

# Milestones
For now, two main milestones have been created:
* RT-Super Lab v1.0: First version of VILLAS framework with minimum required features for EU-USA RT-Super Lab demo.
* RT-Super Lab v2.0: Most likely, the required features for the second milestone will be divided into multiple milestones, but let's keep it simple until we make list of issues for v1.0 and follow up versions.   

@m-mirz Feel free to create milestones for RESERVE demos and deadlines.

---

If we see a need for central Issue Board :) , we could make a single board for all VILLAS projects with open source http://kanban.leanlabs.io/ :)
